# Build main image
FROM python:3.6

WORKDIR /app

# Use python -u/unbuffered setting
ENV PYTHONUNBUFFERED 1

# Install requirements
COPY server/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Must be before static file copies
# https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer
COPY server /app
