# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-07 16:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import organizations.models
import phonenumber_field.modelfields
import rules.contrib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=150)),
                ('street_address_2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(default='Los Angeles', max_length=50)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zipcode', models.CharField(default='90042', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='Invalid zip code format (must be 5 or 9 digits)')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=False)),
                ('ein', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrgUserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', enumfields.fields.EnumIntegerField(default=2, enum=organizations.models.OrgUserRoleType)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='organizations.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='org',
            name='users',
            field=models.ManyToManyField(related_name='orgs', through='organizations.OrgUserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='orguserrole',
            unique_together=set([('user', 'org')]),
        ),
    ]
