# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-18 15:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import organizations.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(max_length=150)),
                ('street_address_2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(default='Los Angeles', max_length=50)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zipcode', models.CharField(default='90042', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='Invalid zip code format (must be 5 or 9 digits)')])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ein', models.CharField(blank=True, max_length=10)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_orgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', enumfields.fields.EnumIntegerField(default=2, enum=organizations.models.OrgUserRole)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Org')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='org',
            name='users',
            field=models.ManyToManyField(related_name='orgs', through='organizations.OrgUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='orguser',
            unique_together=set([('user', 'org')]),
        ),
    ]
