# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_default_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='code',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
