# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20180629_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuptime',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donations.Neighborhood'),
            preserve_default=False,
        ),
    ]
