# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_zipcode_field_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PickupTime',
            new_name='DropoffTime',
        ),
        migrations.RenameField(
            model_name='donationfulfillment',
            old_name='pickup_time',
            new_name='dropoff_time',
        ),
    ]
