# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_rename_pickup_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropofftime',
            name='neighborhood',
        ),
    ]
