# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 16:38
from __future__ import unicode_literals

from django.db import migrations
import donations.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_unique_neighborhood_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropofftime',
            name='day',
            field=enumfields.fields.EnumIntegerField(default=6, enum=donations.models.DaysOfWeek),
        ),
    ]
