# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 01:29
from __future__ import unicode_literals

from django.db import migrations


def delete_null_records(apps, schema_editor):
    DonationFulfillment = apps.get_model('donations', 'DonationFulfillment')
    DonationRequest = apps.get_model('donations', 'DonationRequest')

    # Delete all donation fulfillment with null dropoff time
    DonationFulfillment.objects.filter(dropoff_time=None).delete()

    # Delete all donation requests with null neighborhood
    DonationRequest.objects.filter(neighborhood=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_default_neighborhoods'),
    ]

    operations = [
        migrations.RunPython(
            delete_null_records,
            migrations.RunPython.noop
        ),
    ]
