# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 01:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_delete_null_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationfulfillment',
            name='dropoff_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.DropoffTime'),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.Neighborhood'),
        ),
    ]
