# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 02:36
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_nonnullable_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationfulfillment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
