# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 17:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_location_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maps_url',
            field=models.URLField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationfulfillment',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Los Angeles', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.CharField(default='90042', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='Invalid zip code format (must be 5 or 9 digits)')]),
        ),
    ]
