# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_location_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDropoffDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('dropoff_date', models.DateField(null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_dropoff_dates', to='donations.Location')),
            ],
        ),
    ]
