# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_manualdropoffdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationfulfillment',
            name='manual_dropoff_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.ManualDropoffDate'),
        ),
        migrations.AlterField(
            model_name='donationfulfillment',
            name='dropoff_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.DropoffTime'),
        ),
    ]
