# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0020_fulfillment_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationfulfillment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
