# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-04 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0021_accepted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationfulfillment',
            name='dropoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
