# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 04:04
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0022_allow_blank_dropoff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
