# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-14 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0024_add_org_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='organization_name',
        ),
    ]
