# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-14 23:01
from __future__ import unicode_literals

from django.db import migrations


def delete_locations_with_org(apps, schema_editor):
    Location = apps.get_model('donations', 'Location')

    # Delete locations not associated with an org
    Location.objects.filter(
        org__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0025_remove_location_organization_name'),
    ]

    operations = [
        migrations.RunPython(
            delete_locations_with_org, migrations.RunPython.noop
        )
    ]
