# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-14 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0026_remove_unowned_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.Org'),
        ),
    ]
