# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-18 06:35
from __future__ import unicode_literals

from django.db import migrations


def set_slug_value(apps, schema_editor):
    Category = apps.get_model('donations.Category')
    for category in Category.objects.all():
        category.slug = category.tag
        category.save()


def unset_slug_value(apps, schema_editor):
    Category = apps.get_model('donations.Category')
    for category in Category.objects.all():
        category.tag = category.slug
        category.save()


def recreate_item_types(apps, schema_editor):
    Item = apps.get_model('donations.Item')
    ItemType = apps.get_model('donations.ItemType')

    item_types = []

    for item in Item.objects.all():
        slug = item.tag.replace('_', '-')

        item_types.append(
            ItemType(
                display_name=item.display_name,
                slug=slug,
                category=item.category
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0028_refactor_requests'),
    ]

    operations = [
        migrations.RunPython(
            set_slug_value, unset_slug_value
        ),
        migrations.RunPython(
            recreate_item_types, migrations.RunPython.noop
        ),
    ]
