# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-18 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0029_populate_slugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tag',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
