# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-19 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0030_remove_nonnull_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
