# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-20 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0032_auto_20191019_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
    ]
