# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-22 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0033_auto_20191020_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cancelled',
            new_name='is_cancelled',
        ),
        migrations.RenameField(
            model_name='appointmenttime',
            old_name='cancelled',
            new_name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='size',
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='accepted_terms',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
