# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-22 23:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import donations.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0034_field_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='image',
            field=models.ImageField(validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
