# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0035_auto_20191022_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='valid_appointment_times',
        ),
    ]
