# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0036_remove_donationrequest_valid_appointment_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='valid_appointment_times',
            field=models.ManyToManyField(blank=True, related_name='requests', to='donations.AppointmentTime'),
        ),
    ]
