# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0037_donationrequest_valid_appointment_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
