# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 02:13
from __future__ import unicode_literals

from django.db import migrations
import donations.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0038_appointmenttime_is_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttime',
            name='day_of_week',
            field=enumfields.fields.EnumIntegerField(blank=True, enum=donations.models.DaysOfWeek, null=True),
        ),
    ]
