# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0039_auto_20191022_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttime',
            name='is_ongoing',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
