# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-26 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0042_auto_20191023_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationRequest',
            new_name='Request',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
