# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-27 15:32
from __future__ import unicode_literals

from django.db import migrations
import donations.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0043_auto_20191026_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=enumfields.fields.EnumField(default='w', enum=donations.models.ScheduleType, max_length=1),
        ),
    ]
