# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-27 15:32
from __future__ import unicode_literals

from django.db import migrations
import donations.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0044_event_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='DonorAppointment',
        ),
    ]
