# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-28 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0045_rename_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=16)),
                ('created', models.DateTimeField(auto_now=True)),
                ('fulfillment_items', models.ManyToManyField(related_name='fulfillments', to='donations.FulfillmentItem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillments', to='donations.Request')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='donorappointment',
            name='request',
        ),
        migrations.RemoveField(
            model_name='donorappointment',
            name='request_items',
        ),
        migrations.AddField(
            model_name='donorappointment',
            name='fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_appointments', to='donations.Fulfillment', null=True),
        ),
    ]
