# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-28 03:11
from __future__ import unicode_literals

from django.db import migrations


def delete_invalid_items(apps, schema_editor):
    DonorAppointment = apps.get_model('donations', 'DonorAppointment')
    DonorAppointment.objects.filter(fulfillment__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0046_auto_20191027_1800'),
    ]

    operations = [
        migrations.RunPython(
            delete_invalid_items, migrations.RunPython.noop
        )
    ]
