# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-28 03:24 from __future__ import unicode_literals

from django.db import migrations
from django.db.utils import IntegrityError
from collections import namedtuple


DEFAULT_ITEM_TYPES = {
    ('Clothing', 'clothing'): [
        ('Shirts', 'shirts', 'shirt', False),
        ('Dresses + Skirts', 'dresses_skirts', 'dress/skirt', False),
        ('Hats', 'hats', 'hat', False),
        ('Pants', 'pants', 'pants', True),
        ('Shorts', 'shorts', 'shorts', True),
        ('Jackets + Sweaters', 'jacket_sweaters', 'jackets/sweater', False),
        ('Socks', 'socks', 'socks', True),
        ('Shoes', 'shoes', 'shoes', True),
    ],
    ('Hygiene', 'hygiene'): [
        ('Toothbrush', 'toothbrush', 'toothbrush', False),
        ('Toothpaste', 'toothpaste', 'toothpaste', False),
        ('Mouthwash', 'mouthwash', 'mouthwash', False),
        ('Soap', 'soap', 'soap', False),
        ('Shampoo + Conditioner', 'shampoo_conditioner', 'shampoo/conditioner', False),
        ('Feminine Hygiene', 'feminine_hygiene', 'hygiene product', False),
    ],
    ('Essentials', 'essentials'): [
        ('Blankets', 'blankets', 'blankets', False),
        ('Sleeping Bags', 'sleeping_bags', 'sleeping bag', False),
        ('Cat Food', 'cat_food', 'cat food', False),
        ('Dog Food', 'dog_food', 'dog food', False),
    ]
}


def create_default_item_types(apps, schema_editor):
    Category = apps.get_model('donations', 'Category')
    ItemType = apps.get_model('donations', 'ItemType')

    for ((category_name, category_slug), item_info) in DEFAULT_ITEM_TYPES.items():
        category, _ = Category.objects.get_or_create(display_name=category_name, slug=category_slug)

        for index, (name, slug, inline_text_name, plural_pronoun) in enumerate(item_info):

            # Don't try to create duplicate items
            if ItemType.objects.filter(slug=slug).exists():
                continue

            item_type, _ = ItemType.objects.create(
                display_name=name,
                slug=slug,
                inline_text_name=inline_text_name,
                plural_pronoun=plural_pronoun,
                category=category,
                _order=index)


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0048_make_field_nonnull'),
    ]

    operations = [
        migrations.RunPython(
            create_default_item_types, migrations.RunPython.noop
        ),
    ]
