# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-27 15:32
from __future__ import unicode_literals

from django.db import migrations
import donations.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0049_create_default_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemType',
            new_name='Subcategory',
        ),
    ]
